-- Accounts that can authenticate.
--
-- `GENERATED BY DEFAULT AS IDENTITY` is standard SQL rather than Postgres' BIGSERIAL,
-- so these migrations also run unmodified on H2 (MODE=PostgreSQL) — which is what lets
-- the test suite exercise the real migrations instead of deriving a schema from the
-- entities. BIGINT, not INT: User.id is a Long.
CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
