-- Roles, and the many-to-many link from users to them.
--
-- `roles` is a canonical lookup table: one row per role name, shared by every user that
-- holds it. Names carry the ROLE_ prefix that Spring Security's hasRole(...) prepends
-- when matching, so nothing has to translate between the two forms.
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE
);

-- ON DELETE CASCADE on user_id only: deleting a user drops their grants, but deleting a
-- role that users still hold should be refused rather than silently revoked.
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

INSERT INTO roles (name) VALUES ('ROLE_USER'), ('ROLE_ADMIN');
